POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{"name":"Jeans", "seller":"Chuba"}

### 

GET http://localhost:3000/products/b3dce8a9-290d-4ccd-9873-26208fd73ea3 HTTP/1.1


###

POST http://localhost:3000/sellers HTTP/1.1
content-type: application/json

{"name":"Chuba", "product":"Jeans"}


###

DELETE http://localhost:3000/products/6095408c3986814ef87c3978 HTTP/1.1