POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{"name":"Jeans", "seller":"Chuba", "size": "L", "price": 95} 

###

POST http://localhost:3000/customers HTTP/1.1
content-type: application/json 

{"name":"Kenan", "address":"Baku", "email":"kenan@gmail.com", "order":""} 

###

POST https://backend-c3dff4eucq-ew.a.run.app/sellers HTTP/1.1
content-type: application/json 

{"name":"Chuba", "product":"Jeans"} 

###

DELETE http://localhost:3000/products/6095408c3986814ef87c3978 HTTP/1.1

###

POST http://localhost:3000/customers/60ddb2a72388b221f4398e88/orders HTTP/1.1
content-type: application/json

{"productId": "60dd7544519a1a50206f018c", "name": "Kenan", "address": "Baku", "totalPrice": 58, "orders":""}

###

PATCH http://localhost:3000/products/60dd7544519a1a50206f018c HTTP/1.1
content-type: application/json

{"name": "a newer surname"}

###

PATCH http://localhost:3000/customers/60dd7547519a1a50206f018d HTTP/1.1
content-type: application/json

{"name": "new name4"}