POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{"name":"Jeans", "seller":"Chuba", "size": "L", "price": 95} 

###

POST http://localhost:3000/customers HTTP/1.1
content-type: application/json 

{"name":"Kenan", "address":"Baku", "email":"kenan@gmail.com", "order":""} 

###

POST https://backend-c3dff4eucq-ew.a.run.app/sellers HTTP/1.1
content-type: application/json 

{"name":"Chuba", "product":"Jeans"} 

###

DELETE http://localhost:3000/products/6095408c3986814ef87c3978 HTTP/1.1

###
POST http://localhost:3000/customers/60db86a01bc48e10148bde41/orders HTTP/1.1
content-type: application/json

{"productId": "60db86c31bc48e10148bde42", "address": "Baku", "totalPrice": 58}

###
POST http://localhost:3000/customers/60db86c31bc48e10148bde42/orderings HTTP/1.1
content-type: application/json

{"productId": "60db86a01bc48e10148bde41", "address": "Baku", "totalPrice": 58}